### ISSUE TITLE
Enable dynamic linking in SPM

### ISSUE THREAD

**Issue by jcislinsky** [launchdarkly/swift-eventsource#21]
**Is your feature request related to a problem? Please describe.**

Xcode 12.5 (now in Beta) can resolve packages without specified type as dynamic and therefore resolve an issue with statically linked dependencies in multiple targets (app, extension, …).

But this library defines the static type of package `LDSwiftEventSourceStatic`. And so Xcode is not able to resolve dependencies successfully.

```
Swift package product 'LDSwiftEventSourceStatic' is linked as a static library by 'app' and 'extension'. This will result in duplication of library code.
```

**Describe the solution you'd like**

Keep package type empty or use dynamic.

**Comment by torchhound** [comment]
Hi @jcislinsky thanks for reporting this.

_Filed internally as 104805_

**Comment by gwhelanLD** [comment]
Hi @jcislinsky,

Could I ask you for a bit more clarification around this issue? The [SPM package file](https://github.com/launchdarkly/swift-eventsource/blob/master/Package.swift) defines both a dynamic and static target for this library. Is there something you'd like to see these build products? If your issue is regarding how the [LaunchDarkly iOS SDK](https://github.com/launchdarkly/ios-client-sdk) includes this library as a dependency, could you please file an issue on the SDK issue tracker?

Thanks!
@gwhelanLD

**Comment by gwhelanLD** [comment]
Since we haven't gotten any clarification on this issue, I'll close it for now. Feel free to reopen with more information if you're still running into this issue.

Thanks,
@gwhelanLD
