### ISSUE TITLE
Add a way to disable logging

### ISSUE THREAD

**Issue by choulepoka** [launchdarkly/swift-eventsource#77]
**Is your feature request related to a problem? Please describe.**

Yes. The logging of the LaunchDarkly iOS Client is verbose. When debugging, it is not uncommon to get hundreds of debugging statement in the console, with no easy to disable them.

**Describe the solution you'd like**

Create a way to disable logging, and optionally have the LaunchDarkly iOS Client configure it to match. Ideally somethings like:

`Logs.logger = .disabled`

**Describe alternatives you've considered**

- Swizzling the `Logs` class, but since it is not an objective-c class, it cannot be swizzled
- Forking the library, and replacing the logging code with noop implementations

**Additional context**

Not that I can see.

**Comment by tanderson-ld** [comment]
Hi @choulepoka, thank you for bringing this to our attention.  If I recall correctly, you are using the this in the LaunchDarkly iOS SDK and not standalone.  @keelerm84 [recently updated the logging implementation](https://github.com/launchdarkly/ios-client-sdk/pull/340/files) in the iOS SDK to use os_log which has better filtering capabilities.  Would us bringing this change into the swift-eventsource meet your needs?  We will have to investigate to see if that will work well with pure swift consumers of this event-source.

I have logged a story for tracking this: SC-245493

**Comment by tanderson-ld** [comment]
@choulepoka, we have released version 3.3.0 which supports setting LDEventSource.Config.logger.  We are in the process of updating the iOS SDK to pass it's logger in to the event source when it is created so that one logger is used for both.  That PR is here https://github.com/launchdarkly/ios-client-sdk/pull/390.  Leaving this issue open since I think you are looking for this change in the iOS SDK and not just in this event source repo.

**Comment by tanderson-ld** [comment]
We're still working to get the iOS SDK update out that includes the fix for the iOS SDK itself.

**Comment by tanderson-ld** [comment]
This is now resolved in the iOS Client SDK v9.8.1
